name: Agent Veille Metaux Automation

on:
  schedule:
    - cron: '0 7 * * *' # S'exécute automatiquement tous les jours à 7h00 UTC
  workflow_dispatch: # Permet aussi de le lancer quand tu veux manuellement

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Recuperer le code du depot
        uses: actions/checkout@v4

      - name: 2. Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Installer les bibliotheques necessaires
        run: |
          pip install pandas numpy openpyxl

      - name: 4. Executer l'Agent IA (Analyse & Predictions)
        run: |
          python agent_metaux.py

      - name: 5. Envoyer le rapport par E-mail
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: |
          python send_email.py
